name: platformio build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install platformio
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
    - name: Update libraries
      run: |
        platformio lib update
    - name: Build
      run: |
        platformio run
